### ISSUE TITLE
backup file detection

### ISSUE THREAD

**Issue by random-robbie** [oppsec/juumla#4]
Just as a heads up getting a number of false positives from the zip file backup part.
might need to add mime detection in the response to ensure it's not html

**Comment by 0xdsm** [comment]
Hi, @random-robbie!

First of all, sorry for not providing any support to this issue, I'm not constantly working on this project anymore.

Anyway, I've pushed a new release for juumla which I added a check to the content type on the config and backup files scanner, would you mind checking if everything works now?

Best regards,
oppsec.
